oidc_url                      = "token.actions.githubusercontent.com"
oidc_thumbprint               = "6938fd4d98bab03faadb97b34396831e3780aea1"
oidc_client_id                = "sts.amazonaws.com"
role_name                     = "github-actions-dev"
iam_role_permissions_boundary = "arn:aws:iam::969598603422:policy/netguru-boundary"
project_repository_condition  = "adamkielar/terraform-playground:ref:refs/heads/dev"