name: "Terraform infrastructure deployment"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - dev
      - staging
      - production
  
  workflow_dispatch:
  pull_request:
    
env:
  AWS_REGION: "eu-central-1"

jobs:
  lint:
    name: "Lint terraform code"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.38.1

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

  tfsec:
    name: "Tfsec terraform code"
    runs-on: ubuntu-22.04
    needs: lint
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run Tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --soft-fail
          github_token: ${{ github.token }}

  terraform:
   name: "Terraform"
   runs-on: ubuntu-22.04
   needs: lint
   environment: ${{ github.ref_name }}
   permissions:
      id-token: write
      contents: read 
   defaults:
     run:
       working-directory: ${{ github.ref_name }}
   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          persist-credentials: false

    # Change to OIDC for best practice setup
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        # role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        # role-duration-seconds: 1200
        # role-session-name: Sandbox

    - name: Set terraform version env
      run: echo "TF_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init
