name: "Terraform infrastructure deployment"
concurrency:
  group: infrastructure

on:
  push:
    branches:
      - dev
      - staging
      - production
  
  workflow_dispatch:
  pull_request:
    
env:
  AWS_REGION: "us-east-1"

jobs:
  lint:
    name: "Lint Terraform code"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Cache plugin dir
        uses: actions/cache@v2
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.38.1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

  init-and-plan:
   name: "Terraform init and plan."
   runs-on: ubuntu-22.04
   defaults:
     run:
       working-directory: ${{ github.ref_name }}
   steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Tfenv
      run: |
          git clone https://github.com/tfutils/tfenv.git ./tfenv

    - name: Terraform Init
      run: |
          ./tfenv/bin/tfenv install $(cat .terraform-version) && \
          ./tfenv/bin/tfenv use $(cat .terraform-version) && \
          ./tfenv/bin/terraform init