name: "Terraform infrastructure deployment"
concurrency:
  group: infrastructure

on:
  push:
    branches:
      - dev
      - staging
      - production
  
  workflow_dispatch:
  pull_request:
    
env:
  AWS_REGION: "us-east-1"

jobs:
  # checkout:
  #  name: "Checkout Terraform code"
  #  runs-on: ubuntu-22.04
  #  defaults:
  #    run:
  #      working-directory: ${{ github.ref_name }}
  #  steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Install Tfenv
  #     run: |
  #         git clone https://github.com/tfutils/tfenv.git ./tfenv

  #   - name: Persist to workspace
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: project
  #       path: ~/project

  lint:
    name: "Lint Terraform code"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Setup python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: "Install pre-commit"
        run: pip install -r requirements.txt

      - name: "Run linter"
        run: pre-commit run -av --show-diff-on-failure
    # - name: Terraform Init
    #   run: |
    #       ./tfenv/bin/tfenv install $(cat .terraform-version) && \
    #       ./tfenv/bin/tfenv use $(cat .terraform-version) && \
    #       ./tfenv/bin/terraform init