name: "Terraform infrastructure deployment"
concurrency:
  group: infrastructure

on:
  push:
    branches:
      - dev
      - staging
      - production
  
  workflow_dispatch:
  pull_request:
    
jobs:
  terraform:
   name: "Terraform"
   runs-on: ubuntu-22.04
   defaults:
     run:
       working-directory: ${{ github.ref_name }}
   steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Tfenv
      run: |
          git clone https://github.com/tfutils/tfenv.git ./tfenv

    - name: Terraform Init
      run: |
          ./tfenv/bin/tfenv install $(cat .terraform-version) && \
          ./tfenv/bin/tfenv use $(cat .terraform-version) && \
          ./tfenv/bin/terraform init